### ISSUE TITLE
Create a test suite for MPB interface

### ISSUE THREAD

**Issue by ryanjoneil** [ryanjoneil/SCIP.jl#10]

**Comment by IainNZ** [comment]
I've hooked up the MathProbBase.jl MIP interface test, its not very comprehensive but its a start. The full JuMP test suite will be the eventual goal.

**Comment by ryanjoneil** [comment]
Awesome! How do I invoke that?

**Comment by IainNZ** [comment]
The JuMP test suite? Would need to add SCIP to the list of solvers in JuMP/test/solvers.jl

I'm working on the MPB interface now, it seems like `SCIPvarChgLbOriginal` isn't wrapped, any ideas?

**Comment by ryanjoneil** [comment]
I'll look into it.

**Comment by ryanjoneil** [comment]
So it looks like shouldn't actually be calling that method, since it isn't part of the public interface of SCIP. The methods we should be using for interacting with variables are in [pub_var.h](http://scip.zib.de/doc-2.0.2/html/pub__var_8h.html).
