### ISSUE TITLE
Support SCIP callbacks

### ISSUE THREAD

**Issue by ryanjoneil** [ryanjoneil/SCIP.jl#12]
What this involves is TBD.

**Comment by mlubin** [comment]
@fserra, do you know if constraint handlers must implement [CONSLOCK](http://scip.zib.de/doc/html/CONS.php)? That's a bit of a showstopper for us since we don't and won't ask users to provide this info.

**Comment by fserra** [comment]
yes they have to. wrong behaviour can occur otherwise

why can't users implement this???

maybe you can implement a default method that locks all variable in each
direction? this would not be ideal, but it means being in the safe side....

anyway I'll ask if there is a work around this issue

**Comment by mlubin** [comment]
Well users *could* implement this, but it's not something that we currently require for any other solvers. Locking all variables by default seems reasonable, that's likely what Gurobi and CPLEX do internally when lazy constraint callbacks are present.

**Comment by fserra** [comment]
i am not sure this is true... the idea of locks is that scip doesnt know
whether it can round variable in some direction... i think cplex have the
explicit matrix constraint so they do would not need these locks.
However I still cannot see the problem... i mean if some user wants to
implement a new constraint handler for scip, then of course this is nothing
that is required for any other solver... and if the user is going to
implement say a separation method for its own constraint handler I do not
see why the user cant implement a simple locking callback ;)

but maybe there is something that i am missing...

**Comment by mlubin** [comment]
Cplex and gurobi allow you to provide constraints implicitly through callbacks, so they don't have access to any explicit matrix. We already have lots of code which implement constraint handlers, aka lazy constraint callbacks, (e.g. for [TSP](https://github.com/JuliaOpt/JuMP.jl/blob/master/examples/tsp.jl)), and we want it to be compatible automatically with SCIP.

**Comment by fserra** [comment]
ahhh ok, I see

yes in those cases you could automatically set the variables locked...
but I do not know if it makes sense or if it is possible to have a
particular locks for the constraint handlers you have already implemented...

so for instance in the tsp (at least in the tsp conshdlr implemented in
scip) the locking only represent that you get infesible when rounding up...
and well might be suboptimal to set both roundings

ah ok but I think I now understand the problem.. so you want the user to
write some callbacks and then they could use their constraint handler in
any solver... right?
if this is the case, yes, it is sad that scip needs the locks callback

**Comment by mlubin** [comment]
> so you want the user to
write some callbacks and then they could use their constraint handler in
any solver... right?

Yep, that's the idea

**Comment by joehuchette** [comment]
Since the locking is just based on whether rounding variables up or down can destroy feasibility, can't the SCIP wrapper just provide the handler transparently, based on the signs of the coefficients in the constraint?

**Comment by mlubin** [comment]
@joehuchette, I think it needs to be valid for all constraints that could possibly be generated by the constraint handler

**Comment by joehuchette** [comment]
Can't we just use the custom handler for lazy constraints then?

**Comment by leethargo** [comment]
> Since the locking is just based on whether rounding variables up or down can destroy feasibility, can't the SCIP  wrapper just provide the handler transparently, based on the signs of the coefficients in the constraint?

The problem here is that the constraint concept in SCIP is wider than just linear constraints. There are also nonlinear and logical constraints implemented and users can create all kinds of constraints. Also, the locks have to anticipate the linear inequalities that might be separated later, because the invalid preprocessing would happen at the beginnig of the solving process.
