### ISSUE TITLE
rewrite code generator

### ISSUE THREAD

**Issue by ryanjoneil** [ryanjoneil/SCIP.jl#19]
The Python/lxml code generator is unmaintainable and making it difficult to keep working on SCIP.jl. Port this to something better.

**Comment by mlubin** [comment]
Cool!

**Comment by IainNZ** [comment]
So is the whole C interface wrapped now @ryanjoneil ?

**Comment by ryanjoneil** [comment]
I believe the entire public API for SCIP should be accessible now. If we run into anything that's missing while working on the MPB interface, I can add it reasonably easily.
