### ISSUE TITLE
Some of the SCIP API is missing

### ISSUE THREAD

**Issue by ryanjoneil** [ryanjoneil/SCIP.jl#20]
Moving discussion from #10 to this ticket.

It appears some methods are not being wrapped, for instance `SCIPvarChgLbOriginal`. These are parsed out of the XML generated by Doxygen. Here's how we currently generate that:

```bash
$ cd scipoptsuite-3.1.1/scip-3.1.1/interfaces/jni
scipoptsuite-3.1.1/scip-3.1.1/interfaces/jni$ doxygen jniinterface.dxy
```

This creates an `xml/` directory which we then use to generate the Julia wrappers. When I grep that directory for `SCIPvarChgLbOriginal`, it isn't found.

@fserra: Any idea why this method is not showing up in the Doxygen output?

**Comment by fserra** [comment]
The function is not in the public interface. It is located in var.h and not
in pub_var.h, so users shouldn't use it

**Comment by IainNZ** [comment]
That'd make sense! Is the a way to change problem bounds?

**Comment by ryanjoneil** [comment]
Thanks, @fserra. What method should we be using for this? I see a `SCIPvarSetData` but I'm wondering if there is a public one that is more specific.

**Comment by fserra** [comment]
You can use SCIPchgVarLb/Ub(Global) which is public (in scip.h)
What are you exactly trying to do anyway?

**Comment by IainNZ** [comment]
Just implementing the abstraction layer we have over all the solvers we wrap. Not a great example of a use, but you could imagine using SCIP as part of a larger algorithm where you want to change only the bounds and then resolve.

**Comment by fserra** [comment]
ok. So if the problem is already solved you should first call
SCIPfreeTransform, since you can't change a variables bound when you solved
a problem.

**Comment by ryanjoneil** [comment]
@IainNZ some of the methods you're interested in are wrapped [here](https://github.com/ryanjoneil/SCIP.jl/blob/master/src/wrapped/scip_functions.jl#L4274-L4289).
