### ISSUE TITLE
getsolution()

### ISSUE THREAD

**Issue by kibaekkim** [ryanjoneil/SCIP.jl#21]
I am solving an MILP problem from JuMP. While the problem is successfully solved by SCIP.jl, the following line

``` bash
[src/scip/sol.c:176] ERROR: unknown solution origin <35283200>
```

is printed out after solution. And I am not getting the right solution either.

In line 138 of SCIPSolverInterface.jl, shouldn't it be the following?

``` julia
sol = _SCIPgetBestSol(m.ptr);
```

**Comment by mlubin** [comment]
@kibaekkim, this package is still very experimental, but we welcome your help. Could you submit a pull request with this change?

**Comment by kibaekkim** [comment]
just made a pull-request. @mlubin, I would be happy to help this project.
