### ISSUE TITLE
SCIP solving status enum changed in 3.2

### ISSUE THREAD

**Issue by sbebo** [ryanjoneil/SCIP.jl#23]
In the latest release (3.2) the `SCIP_status` enum has changed, there's a new status SCIP_STATUS_RESTARTLIMIT. It looks like they didn't even mention it in the changelog, but I might be mistaken.
SCIP_STATUS_OPTIMAL, SCIP_STATUS_INFEASIBLE are shifted down, so this breaks things. 
(The MPB tests fail, SCIP returns code 11 which used to be INFEASIBLE -- now it's OPTIMAL..).

**Comment by mlubin** [comment]
Guess we just need to regenerate the interface and bump the minimum supported version?

**Comment by ryanjoneil** [comment]
I can take care of that sometime this weekend.
