### ISSUE TITLE
Prospective GSoC'17 Project ?

### ISSUE THREAD

**Issue by Ayush-iitkgp** [ryanjoneil/SCIP.jl#30]
Hi, 
[Develop a Julia interface to the SCIP solver](https://github.com/numfocus/gsoc/blob/master/2016/ideas-list-juliaopt.md) was listed as GSoC'16 project under NUMFOCUS. I see that the project is yet to be completed. Are you planning to participate in GSoC'17 as well maybe under NUMFOCUS and Julia ? I am interested in this project.

To introduce myself, I am final year graduate student at Indian Institute of Technology, Kharagpur studying Mathematics & Computer Science. Last year, I did GSoC in **Solve complex SDPs with the Convex.jl modeling language**. 

I am tagging prospective mentors @ryanjoneil, @mlubin, @joehuchette and @rgaiacs .

**Comment by ryanjoneil** [comment]
Hi Ayush,

Unfortunately, I haven't had time or reason to use Julia much in the past
couple years due to my work, but if you'd like to take on this project I
could help you get what's there up and running and give you some direction
on where I wanted it to go. I know the JuMP community would love to the
interface completed.

Cheers,
Ryan

**Comment by fserra** [comment]
hi @Ayush-iitkgp @ryanjoneil 

We have a working interface already. Please check https://github.com/SCIP-Interfaces/SCIP.jl

There are, of course, many things to be done. However, I don't know anything about GSoC :(

**Comment by ryanjoneil** [comment]
That's much better!

**Comment by Ayush-iitkgp** [comment]
Thanks! @ryanjoneil, and @fserra. Great to see that SCIP.jl has made great progress since June 2016. 
@fserra [GSoC](http://g.co/gsoc) is a program sponsored by Google where students get paid to write open source code. I am excited to make further additions to the package taking guidance from you, @mlubin and @leethargo. @mlubin would be able to tell us the organization (NUMFOCUS or Julia) under which SCIP.jl can participate in GSoC'17.

**Comment by mlubin** [comment]
I don't intend to have an active role in GSoC'17, but I think both NumFOCUS and Julia would be viable options if you can find a mentor.

**Comment by Ayush-iitkgp** [comment]
@mlubin sad to know that you won't be available to mentor in GSoC'17. I will open an issue in [SCIP-Interfaces](https://github.com/SCIP-Interfaces/SCIP.jl) and see if I can find a mentor :)
